### ISSUE TITLE
A very serious bug.

### ISSUE THREAD

**Issue by YowFung** [MjPaxter/Tcp_Socket_Connection#2]
![image](https://user-images.githubusercontent.com/26346560/113999903-0ebcd880-988d-11eb-8f8e-76a425af05b5.png)

![image](https://user-images.githubusercontent.com/26346560/113999984-24320280-988d-11eb-8ab1-6ab599a10e9a.png)

Use `simpleConnect()` function to create a TCP connection.

**Comment by MjPaxter** [comment]
Thank you very much! I will update the version as soon as I can.

**Comment by MjPaxter** [comment]
I updated the package, I hope now everything is fine.
